import {useEffect,useRef,useState} from 'react';
import type {Case} from '../types';
import {repositoryUrl} from '../config';
import {saveFile,message,sizeLabel} from '../utils';
import {authorizeDrive,disconnectDrive,driveUploadConfigured,loadGoogle,selectDriveFolder,verifyFolder,uploadDriveBlob,shareUploadedFile,type UploadSession} from '../services/driveUpload';
export function DriveUpload({prepared,onBusy}:{prepared:{meta:Case;blob:Blob}|null;onBusy:(busy:boolean)=>void}){
 const [ready,setReady]=useState(false),[connected,setConnected]=useState(false),[folder,setFolder]=useState<{id:string;name:string}|null>(null),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[error,setError]=useState(''),[shared,setShared]=useState(false),[record,setRecord]=useState<object|null>(null);
 const session=useRef<{ct:UploadSession;meta:UploadSession;source:Blob|null}>({ct:{offset:0},meta:{offset:0},source:null}),abort=useRef<AbortController|null>(null);
 useEffect(()=>{if(driveUploadConfigured)void loadGoogle().then(()=>setReady(true)).catch(e=>setError(message(e)));return()=>abort.current?.abort();},[]);
 useEffect(()=>{setRecord(null);setStatus('');session.current={ct:{offset:0},meta:{offset:0},source:prepared?.blob||null};},[prepared]);
 async function connect(){setError('');try{await authorizeDrive();setConnected(true);}catch(e){setError(message(e));}}
 async function choose(){setError('');try{const f=await selectDriveFolder();await verifyFolder(f.id);setFolder(f);session.current={ct:{offset:0},meta:{offset:0},source:prepared?.blob||null};setRecord(null);}catch(e){setError(message(e));}}
 async function upload(){if(!prepared||!folder||!shared)return;setBusy(true);onBusy(true);setError('');const controller=new AbortController();abort.current=controller;try{
  await verifyFolder(folder.id);setStatus('Calculating file checksum…');const digest=await crypto.subtle.digest('SHA-256',await prepared.blob.arrayBuffer());const sha256=Array.from(new Uint8Array(digest),x=>x.toString(16).padStart(2,'0')).join('');controller.signal.throwIfAborted();
  const id=await uploadDriveBlob(prepared.blob,prepared.meta.imaging.filename,folder.id,session.current.ct,n=>setStatus(`Uploading CT · ${sizeLabel(n)} / ${sizeLabel(prepared.blob.size)}`),controller.signal);
  const meta={...prepared.meta,imaging:{...prepared.meta.imaging,sha256},file_id:id};
  setStatus('Uploading report and case metadata…');const metadataId=await uploadDriveBlob(new Blob([JSON.stringify(meta)],{type:'application/json'}),prepared.meta.case_id+'.case.json',folder.id,session.current.meta,()=>{},controller.signal);
  controller.signal.throwIfAborted();setStatus('Enabling link access for these two uploaded files…');await shareUploadedFile(id);await shareUploadedFile(metadataId);
  setRecord({schema:'ct-register-v1',case:meta,metadata_file_id:metadataId});setStatus('Uploaded to Google Drive. Publish the case below to add it to the shared library.');
 }catch(e){setError(controller.signal.aborted?'Upload paused. Keep this page open and click Resume upload.':message(e));}finally{setBusy(false);onBusy(false);abort.current=null;}}
 const body=record?JSON.stringify(record):'';const title=`[CT-REGISTER] ${prepared?.meta.case_id||''}`;const fullUrl=`${repositoryUrl}/issues/new?${new URLSearchParams({title,body})}`;const needsCopy=fullUrl.length>7500;const url=needsCopy?`${repositoryUrl}/issues/new?${new URLSearchParams({title})}`:fullUrl;
 return <div className="form-card"><h2>Upload to Google Drive</h2><p>Connect Google, then select your destination folder (for example, DICOM). Only files created or selected through this app are authorized.</p>{!driveUploadConfigured&&<p role="status" className="note">Google authorization setup is pending. Upload will become available after the administrator configures the OAuth client.</p>}<div className="actions"><button className="button secondary" disabled={!ready||busy} onClick={()=>void connect()}>{connected?'Reconnect Google Drive':'Connect Google Drive'}</button>{connected&&<button className="text-button" disabled={busy} onClick={()=>{disconnectDrive();setConnected(false);setFolder(null);}}>Disconnect</button>}</div><button className="button secondary full" disabled={!connected||busy} onClick={()=>void choose()}>Select destination folder</button>{folder&&<p>Destination: <a href={`https://drive.google.com/drive/folders/${folder.id}`} target="_blank" rel="noreferrer">{folder.name}</a></p>}<label className="checkbox-label"><input type="checkbox" checked={shared} disabled={busy} onChange={e=>setShared(e.target.checked)}/>Allow anyone with a link to read the uploaded CT and report metadata. The folder sharing settings remain unchanged.</label><button className="button primary full" disabled={!prepared||!folder||!connected||!shared||busy||!!record} onClick={()=>void upload()}>{busy?'Uploading…':session.current.ct.url?'Resume upload':'Upload prepared case to Drive'}</button>{!prepared&&<small>Fill in the case and report, then click Prepare Case first.</small>}{busy&&<button className="text-button" onClick={()=>abort.current?.abort()}>Pause upload</button>}{status&&<p role="status">{status}</p>}{error&&<p role="alert" className="error">{error}</p>}{session.current.ct.fileId&&<p><a href={`https://drive.google.com/file/d/${session.current.ct.fileId}/view`} target="_blank" rel="noreferrer">Open uploaded CT</a></p>}{record&&<div className="prepared"><a className="button primary full" href={url} target="_blank" rel="noreferrer">Publish case on GitHub</a>{needsCopy&&<><p>Copy this registration JSON into the GitHub issue body:</p><textarea aria-label="Case registration JSON" readOnly value={body}/></>}<button className="button secondary full" onClick={()=>saveFile(body,prepared!.meta.case_id+'.registration.json','application/json')}>Download registration backup</button><small>Use the repository owner account and click Create on GitHub. The case appears after automatic deployment. Uploading alone does not publish it.</small></div>}<p className="muted">Keep this page open while uploading. Google access tokens are held in memory; reconnect if authorization expires. A paused or failed upload may leave a file in Drive.</p></div>;
}
