import {useState,useId} from 'react';
import {RefreshCw} from 'lucide-react';
import type {CaseRelease,ModelReport,GitHubReview,Decision} from '../types';
import {decisionLabels,ratings} from '../types';
import {submitCaseReviews,updateReview,deleteReview} from '../services/reviews';
type Draft={decision?:Decision;comment:string;submissionId:string};
const empty=():Draft=>({comment:'',submissionId:crypto.randomUUID()});
const valid=(d:Draft)=>ratings.some(value=>value===d.decision);
function DecisionFields({draft,change,busy}:{draft:Draft;change:(p:Partial<Draft>)=>void;busy:boolean}){const groupName=useId();return <><p>Rate the quality of the findings: 1 = Poor, 5 = Excellent.</p><div className="decision-options rating-options" role="radiogroup" aria-label="Findings quality rating">{ratings.map(value=><label key={value} className={`decision rating ${draft.decision===value?'chosen':''}`}><input type="radio" name={groupName} value={value} checked={draft.decision===value} disabled={busy} onChange={()=>change({decision:value})}/>{decisionLabels[value]}</label>)}</div><label>Comment optional<textarea rows={3} value={draft.comment} maxLength={10000} disabled={busy} onChange={e=>change({comment:e.target.value})}/></label></>;}
export function ReviewDecision({item,report,reviews,refresh}:{item:CaseRelease;report:ModelReport;reviews:GitHubReview[];refresh:()=>Promise<void>}){
 const makeDrafts=()=>Object.fromEntries(item.reports.map(r=>[r.id,empty()]));
 const [drafts,setDrafts]=useState<Record<string,Draft>>(makeDrafts),[name,setName]=useState(''),[adding,setAdding]=useState(false);
 const [editing,setEditing]=useState<GitHubReview|null>(null),[editDraft,setEditDraft]=useState<Draft>(empty);
 const [saved,setSaved]=useState<GitHubReview[]>([]),[deleted,setDeleted]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const rows=[...reviews.filter(r=>!saved.some(s=>s.submission_id===r.submission_id)),...saved].filter(r=>!deleted.includes(r.submission_id));
 const groups=new Map<string,GitHubReview[]>();for(const r of rows){const key=r.reviewer.trim();groups.set(key,[...(groups.get(key)||[]),r]);}
 const form=adding||rows.length===0, draft=drafts[report.id];
 const complete=item.reports.filter(r=>valid(drafts[r.id])).length;
 function remember(result:GitHubReview[]){setSaved(all=>[...all.filter(r=>!result.some(s=>s.submission_id===r.submission_id)),...result]);}
 async function perform(action:()=>Promise<void>){setBusy(true);setError('');try{await action();await refresh();}catch(e){setError(e instanceof Error?e.message:'Could not save review.');}finally{setBusy(false);}}
 function submit(){if(busy||!name.trim()||complete!==item.reports.length)return;void perform(async()=>{remember(await submitCaseReviews(item.reports.map(r=>({schema:'ct-review-v1',case_id:item.case_id,release_id:item.release_id,report_id:r.id,model_name:r.model_name,decision:drafts[r.id].decision!,reviewer:name.trim(),comment:drafts[r.id].comment,submission_id:drafts[r.id].submissionId}))));setAdding(false);setName('');setDrafts(makeDrafts());});}
 function remove(r:GitHubReview){if(busy||!window.confirm('Delete this review by '+r.reviewer+'?'))return;void perform(async()=>{await deleteReview(r);setDeleted(all=>[...all,r.submission_id]);setSaved(all=>all.filter(s=>s.submission_id!==r.submission_id));if(editing?.submission_id===r.submission_id)setEditing(null);});}
 function saveEdit(){if(!editing||!valid(editDraft)||busy)return;const original=editing;void perform(async()=>{remember([await updateReview({...original,decision:editDraft.decision!,comment:editDraft.comment},original)]);setEditing(null);});}
 return <div className="decision-panel"><div className="section-heading"><h3>Submitted reviews</h3><button className="icon-button" aria-label="Refresh Reviews" disabled={busy} onClick={()=>void perform(async()=>{setSaved([]);})}><RefreshCw size={15}/></button></div>
 {Array.from(groups,([reviewer,entries])=><section className="reviewer-group" key={reviewer}><h3>{reviewer}</h3>{entries.map(r=><div className="review-feedback" key={r.submission_id}><div><strong>{r.model_name} · Review</strong><span className={`badge ${r.decision}`}>{decisionLabels[r.decision]}</span></div>{editing?.submission_id===r.submission_id?<><DecisionFields draft={editDraft} change={p=>setEditDraft(d=>({...d,...p}))} busy={busy}/><div className="actions"><button className="button primary" disabled={busy||!valid(editDraft)} onClick={saveEdit}>Save changes</button><button className="button secondary" disabled={busy} onClick={()=>setEditing(null)}>Cancel</button></div></>:<>{r.comment&&<p>{r.comment}</p>}<div><small>{new Date(r.created_at).toLocaleString()}</small><span className="actions"><button className="button secondary" disabled={busy||!!editing} onClick={()=>{setEditing(r);setEditDraft({decision:r.decision,comment:r.comment,submissionId:r.submission_id});}}>Edit</button><button className="button secondary" disabled={busy} onClick={()=>remove(r)}>Delete</button></span></div></>}</div>)}</section>)}
 {form?<section className="reviewer-group"><h3>Add review</h3><label>Doctor name required<input value={name} maxLength={100} disabled={busy} onChange={e=>setName(e.target.value)} placeholder="Enter your name" autoComplete="name"/></label><h4>{report.model_name} · Review</h4><DecisionFields draft={draft} change={p=>setDrafts(all=>({...all,[report.id]:{...all[report.id],...p}}))} busy={busy}/><p role="status">{complete} / {item.reports.length} reports ready. Switch report tabs to review each model.</p><button className="button primary full" disabled={busy||!name.trim()||complete!==item.reports.length} onClick={submit}>{busy?'Saving…':'Submit all reports'}</button>{rows.length>0&&<button className="button secondary full" disabled={busy} onClick={()=>setAdding(false)}>Cancel</button>}</section>:<button className="button primary full" disabled={busy} onClick={()=>setAdding(true)}>Add review</button>}
 {error&&<div className="error" role="alert">{error}</div>}</div>;
}
