import {useState,useEffect,lazy,Suspense,useCallback,createContext,useContext} from 'react';
import {HashRouter,Routes,Route,NavLink,Link,useParams} from 'react-router-dom';
import {ScanLine,ArrowUpRight,Plus,RefreshCw,ChevronRight,Check,Minus,X,FileText,Download,Settings as SettingsIcon,ArrowLeft,ExternalLink,FolderOpen,Activity,PanelLeftClose} from 'lucide-react';
import {githubConfig,repositoryUrl} from './config';
import type {CaseRelease,GitHubReview,LocalReview,Decision,Review} from './types';
import {decisionLabels} from './types';
import {listCases} from './services/github/releases';
import {listReviews,buildReviewIssueUrl,reviewsCSV,counts} from './services/github/issues';
import {rateLimitRemaining} from './services/github/githubClient';
import {saveFile,message} from './utils';
import {Upload} from './components/Upload';
import {ViewerBoundary} from './components/ViewerBoundary';
import {Tabs,TabsList,TabsTrigger,TabsContent} from './components/Tabs';
import {ResizablePanelGroup,ResizablePanel,ResizableHandle} from './components/Resizable';
const Viewer=lazy(()=>import('./components/Viewer'));
interface Data {cases:CaseRelease[];reviews:GitHubReview[];loading:boolean;error:string;warnings:string[];refresh:(type?:'cases'|'reviews')=>Promise<void>}
const Context=createContext<Data>(null!);
function DataProvider({children}:{children:React.ReactNode}){const [cases,setCases]=useState<CaseRelease[]>([]),[reviews,setReviews]=useState<GitHubReview[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[warnings,setWarnings]=useState<string[]>([]);const refresh=useCallback(async(type?:'cases'|'reviews')=>{setLoading(true);setError('');try{const [c,r]=await Promise.all([listCases(type!=='reviews'),listReviews(type!=='cases')]);setCases(c.cases);setReviews(r.reviews);setWarnings([...c.warnings,...r.warnings]);}catch(e){setError(message(e));}finally{setLoading(false);}},[]);useEffect(()=>{void refresh();},[refresh]);return <Context.Provider value={{cases,reviews,loading,error,warnings,refresh}}>{children}</Context.Provider>;}
function Banner(){const {error,warnings}=useContext(Context);return <>{error&&<div className="global-error" role="alert">{error}</div>}{!!warnings.length&&<details className="global-warning"><summary>{warnings.length} records need attention</summary>{warnings.map((w,i)=><p key={i}>{w}</p>)}</details>}</>;}
function Header(){return <header className="header"><Link className="brand" to="/"><span className="brand-icon"><ScanLine size={22}/></span><div>CT Report Review<small>CLINICAL RESEARCH</small></div></Link><nav><NavLink to="/cases"><FolderOpen size={15}/>Clinical Review</NavLink><NavLink to="/upload"><Plus size={15}/>Upload Case</NavLink><NavLink to="/results"><Activity size={15}/>Results</NavLink></nav><div className="header-end"><span className="prototype-badge">Research prototype</span><NavLink to="/settings" aria-label="Settings" className="icon-button"><SettingsIcon size={18}/></NavLink></div></header>;}
function Footer(){return <footer className="site-footer"><span>Research Prototype · Use only public, synthetic, or appropriately de-identified imaging data.</span><a href={repositoryUrl} target="_blank" rel="noreferrer">{githubConfig.owner}/{githubConfig.repo}<ExternalLink size={12}/></a></footer>;}
const forCase=(reviews:GitHubReview[],c:CaseRelease)=>reviews.filter(r=>r.case_id===c.case_id&&(!r.release_id||r.release_id===c.release_id));
function Empty(){return <div className="empty"><div className="empty-icon"><ScanLine size={32}/></div><h2>Your review workspace is ready</h2><p>Published CT cases and their model reports will appear here.<br/>Prepare your first case and publish it to GitHub Releases.</p><Link className="button primary" to="/upload"><Plus size={16}/>Upload Case</Link><a href={`${repositoryUrl}/releases`} target="_blank" rel="noreferrer" className="text-button">View GitHub Releases <ArrowUpRight size={14}/></a></div>;}
function CaseTable({compact=false}:{compact?:boolean}){const {cases,reviews,loading}=useContext(Context);if(loading&&!cases.length)return <div className="empty"><span className="spinner"/><p>Loading cases from GitHub…</p></div>;if(!cases.length)return <Empty/>;return <div className="table-scroll"><table><thead><tr><th>Case / study</th><th>Imaging</th><th>Reports</th><th>Date added</th><th>Review status</th><th/></tr></thead><tbody>{cases.slice(0,compact?5:undefined).map(c=>{const reviewed=new Set(forCase(reviews,c).filter(r=>c.reports.some(m=>m.id===r.report_id)).map(r=>r.report_id)).size;return <tr key={c.release_id}><td><Link className="case-title" to={`/review/${c.release_id}`}><span className="study-icon"><ScanLine size={19}/></span><span><strong>{c.case_name}</strong><small>{c.case_id}</small></span></Link></td><td><span className="format-badge">{c.imaging.type==='NIFTI'?'NIfTI':'DICOM'}</span></td><td>{c.reports.length} reports</td><td className="muted">{new Date(c.created_at).toLocaleDateString()}</td><td><div className="review-meter"><span>{reviewed} / {c.reports.length} reviewed</span><progress value={reviewed} max={c.reports.length}/></div></td><td><Link className="review-link" to={`/review/${c.release_id}`}>Review<ChevronRight size={15}/></Link></td></tr>;})}</tbody></table></div>;}
function Home(){const {cases,reviews,loading,refresh}=useContext(Context);return <main className="page home-page"><div className="page-heading"><div><span className="eyebrow">CLINICAL EVALUATION WORKSPACE</span><h1>CT Report Review</h1><p>Clinical evaluation of AI-generated reports against CT imaging data</p></div><Link className="button primary" to="/upload"><Plus size={16}/>Upload Case</Link></div><div className="summary-strip"><div><ScanLine/><span>Published cases<strong>{cases.length}</strong></span></div><div><FileText/><span>Model reports<strong>{cases.reduce((n,c)=>n+c.reports.length,0)}</strong></span></div><div><Check/><span>Submitted reviews<strong>{reviews.length}</strong></span></div><div className="repository-summary"><span className="live-dot"/><span>Shared repository<strong>{githubConfig.owner}/{githubConfig.repo}</strong></span></div></div><section className="work-card"><div className="section-heading"><h2>Case workspace</h2><span className="muted">Published studies</span><button className="button secondary push-right" disabled={loading} onClick={()=>void refresh('cases')}><RefreshCw size={14} className={loading?'spin':''}/>Refresh Cases</button></div><CaseTable compact/></section><div className="home-bottom"><Link to="/cases"><ScanLine size={20}/><div><h3>Clinical Review</h3><p>Inspect the CT study and evaluate each model report.</p></div><ArrowUpRight size={20}/></Link><Link to="/results"><Activity size={20}/><div><h3>Review results</h3><p>Explore individual decisions and export reviewer feedback.</p></div><ArrowUpRight size={20}/></Link></div></main>;}
function Cases(){const {loading,refresh,cases}=useContext(Context);return <main className="page"><div className="page-heading"><div><span className="eyebrow">CLINICAL REVIEW</span><h1>Case library <span className="heading-count">{cases.length}</span></h1><p>Open a study to review its imaging and reports. New releases appear after Pages synchronization completes.</p></div><div className="actions"><button className="button secondary" disabled={loading} onClick={()=>void refresh('cases')}><RefreshCw size={15}/>Refresh Cases</button><Link className="button primary" to="/upload"><Plus size={15}/>Upload Case</Link></div></div><div className="work-card"><CaseTable/></div></main>;}
function ReportPanel({item}:{item:CaseRelease}){
 const {reviews,refresh,loading}=useContext(Context);const [selected,setSelected]=useState(item.reports[0].id);const storageKey=`ct-review:${githubConfig.owner}/${githubConfig.repo}:${item.release_id}`;
 const [local,setLocal]=useState<Record<string,LocalReview>>(()=>{try{return JSON.parse(localStorage.getItem(storageKey)||'{}');}catch{return {};}});const [error,setError]=useState('');const report=item.reports.find(r=>r.id===selected)!;
 useEffect(()=>{try{localStorage.setItem(storageKey,JSON.stringify(local));}catch{setError('Browser storage is unavailable. Keep this tab open until your review is submitted.');}},[local,storageKey]);
 useEffect(()=>{setLocal(prev=>{let changed=false;const next={...prev};Object.entries(prev).forEach(([id,draft])=>{if(draft.status==='Pending GitHub Submission'&&reviews.some(r=>r.submission_id===draft.submission_id&&r.release_id===item.release_id&&r.report_id===id&&r.decision===draft.decision&&r.comment===draft.comment)){next[id]={...draft,status:'Submitted'};changed=true;}});return changed?next:prev;});},[reviews,item.release_id]);
 const draft=local[selected]||{comment:'',submission_id:'',status:'Local' as const};
 function update(patch:Partial<LocalReview>){setError('');setLocal(prev=>({...prev,[selected]:{...draft,...patch,status:'Local',submission_id:crypto.randomUUID()}}));}
 const related=forCase(reviews,item);const submitted=related.filter(r=>r.report_id===selected);
 const reviewed=item.reports.filter(r=>{const d=local[r.id];return d?.decision&&(d.decision!=='PARTIAL_ACCEPT'||d.comment.trim())||related.some(v=>v.report_id===r.id);}).length;
 function submit(){if(!draft.decision)return;try{const r:Review={schema:'ct-review-v1',case_id:item.case_id,release_id:item.release_id,report_id:report.id,model_name:report.model_name,decision:draft.decision,comment:draft.comment,submission_id:draft.submission_id||crypto.randomUUID()};const {url,body}=buildReviewIssueUrl(r);if(url.length>7500){saveFile(body,`${item.case_id}-${report.id}-review.md`);setError('Review text is too long for a prefilled URL. Copy the downloaded Markdown into a new GitHub issue; keep the JSON block intact.');window.open(`${repositoryUrl}/issues/new?title=${encodeURIComponent(`[CT-REVIEW] ${item.case_id} | ${report.id} | ${r.decision}`)}`,'_blank','noopener,noreferrer');}else{window.open(url,'_blank','noopener,noreferrer');}setLocal(prev=>({...prev,[selected]:{...draft,submission_id:r.submission_id,status:'Pending GitHub Submission'}}));}catch(e){setError(message(e));}}
 return <aside className="report-panel"><div className="panel-header"><div><FileText size={16}/><h2>Model reports</h2></div><span>{reviewed} / {item.reports.length} reviewed</span></div><Tabs value={selected} onValueChange={setSelected} className="report-tabs"><TabsList aria-label="Model reports">{item.reports.map(r=><TabsTrigger value={r.id} key={r.id}>{r.model_name}{local[r.id]?.decision&&<span className={`decision-dot ${local[r.id].decision}`}/>}</TabsTrigger>)}</TabsList>{item.reports.map(r=><TabsContent key={r.id} value={r.id} className="report-content"><span className="eyebrow">AI-GENERATED REPORT</span><div className="report-title"><h3>{r.report_name}</h3><button className="icon-button" title="Download Report" aria-label={`Download ${r.model_name} report`} onClick={()=>saveFile(r.report_text,`${item.case_id}-${r.id}.txt`)}><Download size={16}/></button></div><div className="report-text">{r.report_text}</div></TabsContent>)}</Tabs>
 <div className="decision-panel"><div className="section-heading"><h3>Your review</h3><span className={`badge ${draft.status==='Submitted'?'good':''}`}>{draft.status}</span></div><div className="decision-options" role="radiogroup" aria-label="Review decision">{([['ACCEPT',Check],['PARTIAL_ACCEPT',Minus],['REJECT',X]] as const).map(([d,Icon])=><button key={d} role="radio" aria-checked={draft.decision===d} className={`decision ${d} ${draft.decision===d?'chosen':''}`} onClick={()=>update({decision:d})}><Icon size={16}/>{d==='PARTIAL_ACCEPT'?'Partial':decisionLabels[d]}</button>)}</div><label>Comment {draft.decision==='PARTIAL_ACCEPT'?<span className="required">required</span>:<span className="muted">optional</span>}<textarea rows={3} value={draft.comment} onChange={e=>update({comment:e.target.value})} placeholder={draft.decision==='PARTIAL_ACCEPT'?'Describe which findings are correct and what needs revision…':'Add clinical feedback…'}/></label><button className="button primary full" disabled={!draft.decision||draft.decision==='PARTIAL_ACCEPT'&&!draft.comment.trim()} onClick={submit}>Submit Review<ArrowUpRight size={15}/></button><small>Opens GitHub. Click “Create” there to submit your issue.</small>{error&&<div className="error" role="alert">{error}</div>}</div>
 <div className="submitted-panel"><div className="section-heading"><h3>Reviewer feedback <span className="muted">{submitted.length}</span></h3><button className="icon-button" aria-label="Refresh Reviews" title="Refresh Reviews" disabled={loading} onClick={()=>void refresh('reviews')}><RefreshCw size={15}/></button></div>{!submitted.length?<p className="muted">No submitted reviews for this report.</p>:submitted.map(r=><div className="review-feedback" key={r.github_issue_number}><div><strong>@{r.reviewer}</strong><span className={`badge ${r.decision}`}>{decisionLabels[r.decision]}</span></div>{r.comment&&<p>{r.comment}</p>}<a href={r.url} target="_blank" rel="noreferrer">{new Date(r.created_at).toLocaleString()} · #{r.github_issue_number}</a></div>)}</div></aside>;
}
function ReviewPage(){const {caseId}=useParams();const {cases,loading,reviews}=useContext(Context);const item=cases.find(c=>c.release_id===Number(caseId));if(!item)return <main className="page"><div className="empty"><ScanLine size={32}/><h2>{loading?'Loading case…':'Case not found'}</h2><Link to="/cases" className="button secondary">Back to cases</Link></div></main>;return <main className="review-page"><div className="review-topbar"><Link to="/cases" className="icon-button" aria-label="Back to cases"><ArrowLeft size={18}/></Link><span className="case-id">{item.case_id}</span><strong>{item.case_name}</strong><span className="format-badge">{item.imaging.type}</span><span className="muted push-right">{item.reports.length} model reports</span><a href={item.release_url} target="_blank" rel="noreferrer" className="text-button">Release<ExternalLink size={13}/></a></div><ResizablePanelGroup direction="horizontal" className="review-layout"><ResizablePanel defaultSize={15} minSize={10} maxSize={24}><aside className="case-sidebar"><div className="panel-header"><h2>Cases <span>{cases.length}</span></h2><PanelLeftClose size={15}/></div>{cases.map(c=><Link key={c.release_id} to={`/review/${c.release_id}`} className={`case-item ${c.release_id===item.release_id?'active':''}`}><div><span className="mini-study"><ScanLine size={22}/></span><span><strong>{c.case_id}</strong><small>{c.imaging.type}</small></span><ChevronRight size={14}/></div><p>{c.case_name}</p><small>{new Set(forCase(reviews,c).map(r=>r.report_id)).size} / {c.reports.length} reviewed</small></Link>)}</aside></ResizablePanel><ResizableHandle/><ResizablePanel defaultSize={55} minSize={35}><ViewerBoundary key={item.release_id}><Suspense fallback={<div className="empty"><span className="spinner"/>Loading imaging engine…</div>}><Viewer key={item.release_id} item={item}/></Suspense></ViewerBoundary></ResizablePanel><ResizableHandle/><ResizablePanel defaultSize={30} minSize={23} maxSize={45}><ReportPanel key={item.release_id} item={item}/></ResizablePanel></ResizablePanelGroup></main>;}
function Results(){const {reviews,cases,loading,refresh}=useContext(Context);const overall=counts(reviews);const names=new Map(cases.flatMap(c=>[[c.case_id,c.case_name],[String(c.release_id),c.case_name]]));const groups=new Map<string,GitHubReview[]>();reviews.forEach(r=>{const key=`${r.release_id}:${r.case_id}:${r.report_id}`;groups.set(key,[...(groups.get(key)||[]),r]);});return <main className="page"><div className="page-heading"><div><span className="eyebrow">REVIEW ANALYSIS</span><h1>Review results</h1><p>Individual clinician decisions, synchronized from GitHub Issues.</p></div><div className="actions"><button className="button secondary" disabled={loading} onClick={()=>void refresh('reviews')}><RefreshCw size={15}/>Refresh Reviews</button><button className="button secondary" onClick={()=>saveFile(JSON.stringify(reviews,null,2),'reviews.json','application/json')}><Download size={15}/>JSON</button><button className="button primary" onClick={()=>saveFile(reviewsCSV(reviews,names),'reviews.csv','text/csv')}><Download size={15}/>CSV</button></div></div><div className="summary-strip results-counts"><div><FileText/><span>Submitted reviews<strong>{reviews.length}</strong></span></div><div><Check/><span>Accept<strong>{overall.ACCEPT}</strong></span></div><div><Minus/><span>Partial<strong>{overall.PARTIAL_ACCEPT}</strong></span></div><div><X/><span>Reject<strong>{overall.REJECT}</strong></span></div></div>{!reviews.length?<div className="work-card empty"><Activity size={30}/><h2>No reviews submitted yet</h2><p>Published GitHub review issues will appear here after you refresh.</p><Link className="button secondary" to="/cases">Open Clinical Review<ChevronRight size={15}/></Link></div>:[...groups].map(([key,rs])=>{const c=counts(rs);return <section className="work-card results-group" key={key}><div className="section-heading"><span className="case-id">{rs[0].case_id}</span><h2>{rs[0].model_name}</h2><span className="muted">{rs[0].report_id}</span><div className="actions push-right"><span className="badge ACCEPT">Accept: {c.ACCEPT}</span><span className="badge PARTIAL_ACCEPT">Partial: {c.PARTIAL_ACCEPT}</span><span className="badge REJECT">Reject: {c.REJECT}</span></div></div><div className="table-scroll"><table><thead><tr><th>Reviewer</th><th>Decision</th><th>Comment</th><th>Submitted</th><th>Issue</th></tr></thead><tbody>{rs.map(r=><tr key={r.github_issue_number}><td>@{r.reviewer}</td><td><span className={`badge ${r.decision}`}>{decisionLabels[r.decision]}</span></td><td className="comment-cell">{r.comment||'—'}</td><td>{new Date(r.created_at).toLocaleDateString()}</td><td><a href={r.url} target="_blank" rel="noreferrer">#{r.github_issue_number}<ArrowUpRight size={12}/></a></td></tr>)}</tbody></table></div></section>;})}</main>;}
function Settings(){return <main className="page settings-page"><div className="page-heading"><div><span className="eyebrow">WORKSPACE CONFIGURATION</span><h1>Settings</h1><p>GitHub is the shared storage and communication layer.</p></div></div><div className="form-card"><h2>Connected repository</h2><div className="settings-row"><span>Owner</span><strong>{githubConfig.owner}</strong></div><div className="settings-row"><span>Repository</span><strong>{githubConfig.repo}</strong></div><div className="settings-row"><span>API requests remaining</span><strong>{rateLimitRemaining??'Not available'}</strong></div><a href={repositoryUrl} target="_blank" rel="noreferrer" className="button secondary">Open repository<ExternalLink size={15}/></a></div><div className="form-card"><h2>Publishing & authentication</h2><p>Publish prepared case files through GitHub Releases using your existing GitHub account. This website does not request or store administrator tokens.</p><p>Clinicians can read public cases without signing in. Reviews are submitted on GitHub under the clinician’s own account.</p><p className="muted">To change the shared repository, edit github.config.json and deploy the application. Local review drafts stay in this browser; confirmed reviews are read from GitHub Issues.</p></div><div className="note">Research Prototype. Use only public, synthetic, or appropriately de-identified imaging data. Public repository assets and review comments are visible to everyone.</div></main>;}
export default function App(){return <HashRouter><DataProvider><Header/><Banner/><Routes><Route path="/" element={<Home/>}/><Route path="/cases" element={<Cases/>}/><Route path="/upload" element={<Upload/>}/><Route path="/review/:caseId" element={<ReviewPage/>}/><Route path="/results" element={<Results/>}/><Route path="/settings" element={<Settings/>}/><Route path="*" element={<Cases/>}/></Routes><Footer/></DataProvider></HashRouter>;}
